
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Software/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:24 (project)"
    message: |
      The system is: Windows - 10.0.22000 - 
...
